source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!


target 'Marvel' do
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireObjectMapper', '~> 4.0.1'
    pod 'AlamofireImage', '~> 3.3'
end




